### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by grekier** [math-nao/certs#1]
Hi.

I came across this project and thought I would try it but came across a couple of issues that I see in the code. You have hardcoded the namespace to app in the following files:
- certs/templates/rolebinding.yaml
- certs/templates/serviceaccount.yaml
- certs/templates/role.yaml

This results in error when trying to install the chart in another namespace. I thought I'd let you know.

**Comment by math-nao** [comment]
Hi @grekier,

Thank you for reporting this issue.

This issue has been fixed in dev branch and I released v1.0.1

Let me know when you will try this new version. (Don't forget to update helm repo)
