### ISSUE TITLE
chart: schedule value does not work with some expressions

### ISSUE THREAD

**Issue by vkruoso** [math-nao/certs#10]
I've been testing certs in a test cluster and in general it works great. I want to react to ingress changes in a fast way, So I want the verification job to run as fast as possible since there is no reaction from ingress changes implemented.

Im not sure this is a general helm problem, but using the chart and setting the value below, the chart installation errors out with yaml parsing error:

```
schedule: "*/2 * * * *"
```

I need to change the value to the more verbose format below to the template to render:

```
schedule: "0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58 * * * *"
```

**Comment by math-nao** [comment]
Could you please share errors message you received?

**Comment by vkruoso** [comment]
Sorry for not providing it before. Here it is:
```
Error: UPGRADE FAILED: YAML parse error on certs/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 10: did not find expected alphabetic or numeric character
```

Looks like its expecting a-zA-Z0-9 only for the first character in the value. Not sure if this is a helm issue or is there any other standards to provide that kind of value in yaml.

**Comment by math-nao** [comment]
I can install certs with the same schedule value than yours. What helm version are you using?

I delivered an update on dev branch, could you please give a try with this branch?

**Comment by math-nao** [comment]
I released a new version. Could you give a try?

**Comment by vkruoso** [comment]
Im using helm v2.10.0 within Rancher v2.2.4. Will give it a try with the most recent versions of all components.

**Comment by math-nao** [comment]
@vkruoso do you have news?

**Comment by vkruoso** [comment]
Hi @math-nao . Sorry for the delay. I cloud not test it again. It may be a problem with Helm or Rancher itself, since from the template that looks unrelated to certs implementation. I'll close this issue for now and if I have more information I'll get back here. Thanks for taking the time and for the tool itself.
