### ISSUE TITLE
Invalid status code found: 

### ISSUE THREAD

**Issue by debianmaster** [math-nao/certs#15]
```
k logs -f certs-manually-20191109-103114-m84w9
wait few seconds in case ingress rule is deployed at the same as it is in demo
Info: Initialize environment...
Info: Invalid status code found: ```

values.yaml


```
schedule: "0 2,14 * * *"

env:
- name: AWS_ACCESS_KEY_ID
  value: redacted 
- name: AWS_SECRET_ACCESS_KEY
  value: redacted
```

**Comment by math-nao** [comment]
Hi @debianmaster, it may be related to http protocol used by k8s api server on your environment. I released a new version to allow http/1.1 as well. Could you give a try with the latest version?

**Comment by math-nao** [comment]
@debianmaster, any news?

**Comment by debianmaster** [comment]
@math-nao   did not get time to test this.   if i try on next cluster i will let you know
