### ISSUE TITLE
Errors with K3S cluster

### ISSUE THREAD

**Issue by AnsonT** [math-nao/certs#20]
Kubernetes API version: v1.17.2+k3s1
OS: Ubuntu Server 18.04.4 LTS
helm: 3.1.1

`helm install   --namespace app   --values values.yaml certs  certs/certs`

Gives the following error:
`
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Job.spec.template.spec): unknown field "backoffLimit" in io.k8s.api.core.v1.PodSpec, ValidationError(Job.spec.template.spec): unknown field "concurrencyPolicy" in io.k8s.api.core.v1.PodSpec, ValidationError(Job.spec.template.spec): unknown field "ttlSecondsAfterFinished" in io.k8s.api.core.v1.PodSpec]
`

**Comment by reloaded** [comment]
I ran into this same issue yesterday and got around it by copying the helm chart and modifying it to fix the bug. I'll submit a PR that fixes this in the next 24 hours.

@math-nao

**Comment by reloaded** [comment]
PR submitted. 

https://github.com/math-nao/certs/pull/22

@math-nao @AnsonT

**Comment by math-nao** [comment]
Thanks @reloaded 
@AnsonT could you please try with latest version (1.1.4)?

**Comment by reloaded** [comment]
@math-nao  FWIW I deployed the latest helm chart and verified this bug is fixed as well as #21

**Comment by math-nao** [comment]
@reloaded thank you
