### ISSUE TITLE
K8S 1.22 support

### ISSUE THREAD

**Issue by 3dbrows** [math-nao/certs#51]
The URI to the `ingresses` API is hard-coded to `/apis/extensions/v1beta1` here: https://github.com/math-nao/certs/blob/master/scripts/certs.sh#L174

This is deprecated and removed in K8S 1.22. To continue to work with 1.22, it should be changed to `/apis/networking.k8s.io/v1`.

RBAC rules must also be updated such that the `networking.k8s.io` API group is accessible, rather than `extensions`.

I can submit a PR if you'd like, but I'm not sure exactly how you would wish to maintain backwards compatibility.

Thank you for the excellent repo.

**Comment by retoo** [comment]
@math-nao please merge the PR #52 – everything is ready.

otherwise, please at least warn users not to use this chart for k8s >= 1.22, but that would be a shame :/
